// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEY0GjTNGJD1vKv73MwoHzNnMTsiSUOxk',
    appId: '1:59182831756:web:9d8730af1eb9b265a603a9',
    messagingSenderId: '59182831756',
    projectId: 'wasteagram-328c0',
    authDomain: 'wasteagram-328c0.firebaseapp.com',
    storageBucket: 'wasteagram-328c0.appspot.com',
    measurementId: 'G-4ZPSYCDJX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4R5uph42t0hDMYb9aP6m1mtuRolQEcU8',
    appId: '1:59182831756:android:709a3566c28f7ac6a603a9',
    messagingSenderId: '59182831756',
    projectId: 'wasteagram-328c0',
    storageBucket: 'wasteagram-328c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9Yc88QjEinGJf2YOSbitbwfwzwqwHtSE',
    appId: '1:59182831756:ios:82ce77ee4af33433a603a9',
    messagingSenderId: '59182831756',
    projectId: 'wasteagram-328c0',
    storageBucket: 'wasteagram-328c0.appspot.com',
    iosClientId: '59182831756-gnuk3ljpcqcj6uihs3pd6uber51p6j2p.apps.googleusercontent.com',
    iosBundleId: 'edu.oregonstate.bochansz.wasteagram',
  );
}
